// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using deliverycart.Data;

#nullable disable

namespace deliverycart1.Migrations
{
    [DbContext(typeof(Context))]
    [Migration("20220223013446_initialCreate")]
    partial class initialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "6.0.2");

            modelBuilder.Entity("deliverycart.Models.Item", b =>
                {
                    b.Property<int>("ItemID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("VendorID")
                        .HasColumnType("INTEGER");

                    b.Property<string>("itemName")
                        .HasColumnType("TEXT");

                    b.Property<int>("itemQty")
                        .HasColumnType("INTEGER");

                    b.HasKey("ItemID");

                    b.HasIndex("VendorID");

                    b.ToTable("Item");
                });

            modelBuilder.Entity("deliverycart.Models.Order", b =>
                {
                    b.Property<int>("OrderID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("ItemID")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Qty")
                        .HasColumnType("INTEGER");

                    b.Property<int>("UserID")
                        .HasColumnType("INTEGER");

                    b.HasKey("OrderID");

                    b.HasIndex("ItemID");

                    b.ToTable("Order");
                });

            modelBuilder.Entity("deliverycart.Models.Vendor", b =>
                {
                    b.Property<int>("VendorID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("storeAddress")
                        .HasColumnType("TEXT");

                    b.Property<string>("storeCity")
                        .HasColumnType("TEXT");

                    b.Property<string>("storeName")
                        .HasColumnType("TEXT");

                    b.Property<string>("storeState")
                        .HasColumnType("TEXT");

                    b.Property<int>("storeZip")
                        .HasColumnType("INTEGER");

                    b.HasKey("VendorID");

                    b.ToTable("Vendor");
                });

            modelBuilder.Entity("deliverycart.Models.Item", b =>
                {
                    b.HasOne("deliverycart.Models.Vendor", "Vendor")
                        .WithMany("Items")
                        .HasForeignKey("VendorID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Vendor");
                });

            modelBuilder.Entity("deliverycart.Models.Order", b =>
                {
                    b.HasOne("deliverycart.Models.Item", null)
                        .WithMany("Orders")
                        .HasForeignKey("ItemID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("deliverycart.Models.Item", b =>
                {
                    b.Navigation("Orders");
                });

            modelBuilder.Entity("deliverycart.Models.Vendor", b =>
                {
                    b.Navigation("Items");
                });
#pragma warning restore 612, 618
        }
    }
}
